### ISSUE TITLE
The spymaster should be able to close the dialog to inspect the board.

### ISSUE THREAD

**Issue by deesejohn** [deesejohn/distributed-codenames#16]
@skinney87 if you checkout PR #14 you'll notice the dialog is blocking the board. I want to allow the spymaster to dismiss the dialog to see the board, and then reopen the dialog with a button at the top. Feels kind of weird though. Let me know if you can think of a better UX there. Maybe the form should just be at the top instead? Dunno. Let me know if you have time to take a look.

**Comment by skinney87** [comment]
@deesejohn I haven't checked out the PR yet but I understand what you are saying. At the moment I feel like it should be at the top. What are your thoughts on a scoreboard/info board above the playing board that could be a container for elements like this?

**Comment by deesejohn** [comment]
I was thinking along those lines too. I did have two concerns:
1. I don't want to take up too much screen space on mobile
2. I want to make sure the spymaster is clearly aware when the game is waiting on them to provide a hint

**Comment by skinney87** [comment]
Yeah I've been wondering about how we want to handle mobile as well. I think at that point we will need to cover the board in some manner to show the dialog and other details.

**Comment by skinney87** [comment]
@deesejohn Would you like me to mess around with the positioning of the the form here? I might try working it into a scoreboard/info board section as mentioned previously.
