### ISSUE TITLE
End game if team reveals all of their words

### ISSUE THREAD

**Issue by deesejohn** [deesejohn/distributed-codenames#4]
The game should end if a team guesses all of the words matching their team's color. That team becomes the winner.

**Comment by deesejohn** [comment]
Updated the game svc and bff. Still need a winning message in the game spa. @skinney87, you have time to add that?

**Comment by skinney87** [comment]
Sure, I can work on the game_spa today. @deesejohn

**Comment by skinney87** [comment]
@deesejohn Made a commit but forgot to tag it with this issue. At this point I just have the board replaced by a message once a team wins.
